spring.application.name=agent trust ledger
spring.application.name=agent-trust-ledger

spring.datasource.url=jdbc:postgresql://localhost:5432/agent_trust_ledger
spring.datasource.username=anuskajaiswal
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
